version: "3"

services:
 application:
  image: springboot-app
  ports: 
   - 8080:8080
  networks: 
   - springboot-db-network
  depends_on:
   - mysqldb
  volumes:
   - data/springboot_app

 mysqldb:
  image: mysql:8.0.36
  networks:
   - springboot-db-network
  environment:
   - MYSQL_ROOT_PASSWORD=13321332
   - MYSQL_DATABASE=docker
  volumes:
   - data/mysql

networks:
 springboot-db-network:
